StockDataStream:
  quotes:
    active: true
    handler: quote_data_handler
    subscription: subscribe_quotes
    tickers:
      - AAPL
  trades:
    active: true
    handler: trade_data_handler
    subscription: subscribe_trades
    tickers:
      - AAPL